# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:46:11+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class RestrictedMetricType(Enum):
    RESTRICTED_METRIC_TYPE_UNSPECIFIED = 'RESTRICTED_METRIC_TYPE_UNSPECIFIED'
    COST_DATA = 'COST_DATA'
    REVENUE_DATA = 'REVENUE_DATA'


class ActiveMetricRestriction(BaseModel):
    metricName: Optional[str] = Field(
        None, description='The name of the restricted metric.'
    )
    restrictedMetricTypes: Optional[List[RestrictedMetricType]] = Field(
        None, description="The reason for this metric's restriction."
    )


class CaseExpression(BaseModel):
    dimensionName: Optional[str] = Field(
        None,
        description='Name of a dimension. The name must refer back to a name in dimensions field of the request.',
    )


class CompatibilityFilter(Enum):
    COMPATIBILITY_UNSPECIFIED = 'COMPATIBILITY_UNSPECIFIED'
    COMPATIBLE = 'COMPATIBLE'
    INCOMPATIBLE = 'INCOMPATIBLE'


class CohortReportSettings(BaseModel):
    accumulate: Optional[bool] = Field(
        None,
        description='If true, accumulates the result from first touch day to the end day. Not supported in `RunReportRequest`.',
    )


class Granularity(Enum):
    GRANULARITY_UNSPECIFIED = 'GRANULARITY_UNSPECIFIED'
    DAILY = 'DAILY'
    WEEKLY = 'WEEKLY'
    MONTHLY = 'MONTHLY'


class CohortsRange(BaseModel):
    endOffset: Optional[int] = Field(
        None,
        description='Required. `endOffset` specifies the end date of the extended reporting date range for a cohort report. `endOffset` can be any positive integer but is commonly set to 5 to 10 so that reports contain data on the cohort for the next several granularity time periods. If `granularity` is `DAILY`, the `endDate` of the extended reporting date range is `endDate` of the cohort plus `endOffset` days. If `granularity` is `WEEKLY`, the `endDate` of the extended reporting date range is `endDate` of the cohort plus `endOffset * 7` days. If `granularity` is `MONTHLY`, the `endDate` of the extended reporting date range is `endDate` of the cohort plus `endOffset * 30` days.',
    )
    granularity: Optional[Granularity] = Field(
        None,
        description='Required. The granularity used to interpret the `startOffset` and `endOffset` for the extended reporting date range for a cohort report.',
    )
    startOffset: Optional[int] = Field(
        None,
        description='`startOffset` specifies the start date of the extended reporting date range for a cohort report. `startOffset` is commonly set to 0 so that reports contain data from the acquisition of the cohort forward. If `granularity` is `DAILY`, the `startDate` of the extended reporting date range is `startDate` of the cohort plus `startOffset` days. If `granularity` is `WEEKLY`, the `startDate` of the extended reporting date range is `startDate` of the cohort plus `startOffset * 7` days. If `granularity` is `MONTHLY`, the `startDate` of the extended reporting date range is `startDate` of the cohort plus `startOffset * 30` days.',
    )


class ConcatenateExpression(BaseModel):
    delimiter: Optional[str] = Field(
        None,
        description='The delimiter placed between dimension names. Delimiters are often single characters such as "|" or "," but can be longer strings. If a dimension value contains the delimiter, both will be present in response with no distinction. For example if dimension 1 value = "US,FR", dimension 2 value = "JP", and delimiter = ",", then the response will contain "US,FR,JP".',
    )
    dimensionNames: Optional[List[str]] = Field(
        None,
        description='Names of dimensions. The names must refer back to names in the dimensions field of the request.',
    )


class DateRange(BaseModel):
    endDate: Optional[str] = Field(
        None,
        description="The inclusive end date for the query in the format `YYYY-MM-DD`. Cannot be before `start_date`. The format `NdaysAgo`, `yesterday`, or `today` is also accepted, and in that case, the date is inferred based on the property's reporting time zone.",
    )
    name: Optional[str] = Field(
        None,
        description='Assigns a name to this date range. The dimension `dateRange` is valued to this name in a report response. If set, cannot begin with `date_range_` or `RESERVED_`. If not set, date ranges are named by their zero based index in the request: `date_range_0`, `date_range_1`, etc.',
    )
    startDate: Optional[str] = Field(
        None,
        description="The inclusive start date for the query in the format `YYYY-MM-DD`. Cannot be after `end_date`. The format `NdaysAgo`, `yesterday`, or `today` is also accepted, and in that case, the date is inferred based on the property's reporting time zone.",
    )


class Compatibility(Enum):
    COMPATIBILITY_UNSPECIFIED = 'COMPATIBILITY_UNSPECIFIED'
    COMPATIBLE = 'COMPATIBLE'
    INCOMPATIBLE = 'INCOMPATIBLE'


class DimensionExpression(BaseModel):
    concatenate: Optional[ConcatenateExpression] = Field(
        None,
        description='Used to combine dimension values to a single dimension. For example, dimension "country, city": concatenate(country, ", ", city).',
    )
    lowerCase: Optional[CaseExpression] = Field(
        None, description='Used to convert a dimension value to lower case.'
    )
    upperCase: Optional[CaseExpression] = Field(
        None, description='Used to convert a dimension value to upper case.'
    )


class DimensionHeader(BaseModel):
    name: Optional[str] = Field(None, description="The dimension's name.")


class DimensionMetadata(BaseModel):
    apiName: Optional[str] = Field(
        None,
        description="This dimension's name. Useable in [Dimension](#Dimension)'s `name`. For example, `eventName`.",
    )
    category: Optional[str] = Field(
        None,
        description='The display name of the category that this dimension belongs to. Similar dimensions and metrics are categorized together.',
    )
    customDefinition: Optional[bool] = Field(
        None,
        description='True if the dimension is a custom dimension for this property.',
    )
    deprecatedApiNames: Optional[List[str]] = Field(
        None,
        description='Still usable but deprecated names for this dimension. If populated, this dimension is available by either `apiName` or one of `deprecatedApiNames` for a period of time. After the deprecation period, the dimension will be available only by `apiName`.',
    )
    description: Optional[str] = Field(
        None, description='Description of how this dimension is used and calculated.'
    )
    uiName: Optional[str] = Field(
        None,
        description="This dimension's name within the Google Analytics user interface. For example, `Event name`.",
    )


class OrderType(Enum):
    ORDER_TYPE_UNSPECIFIED = 'ORDER_TYPE_UNSPECIFIED'
    ALPHANUMERIC = 'ALPHANUMERIC'
    CASE_INSENSITIVE_ALPHANUMERIC = 'CASE_INSENSITIVE_ALPHANUMERIC'
    NUMERIC = 'NUMERIC'


class DimensionOrderBy(BaseModel):
    dimensionName: Optional[str] = Field(
        None, description='A dimension name in the request to order by.'
    )
    orderType: Optional[OrderType] = Field(
        None, description='Controls the rule for dimension value ordering.'
    )


class DimensionValue(BaseModel):
    value: Optional[str] = Field(
        None, description='Value as a string if the dimension type is a string.'
    )


class InListFilter(BaseModel):
    caseSensitive: Optional[bool] = Field(
        None, description='If true, the string value is case sensitive.'
    )
    values: Optional[List[str]] = Field(
        None, description='The list of string values. Must be non-empty.'
    )


class Metric(BaseModel):
    expression: Optional[str] = Field(
        None,
        description='A mathematical expression for derived metrics. For example, the metric Event count per user is `eventCount/totalUsers`.',
    )
    invisible: Optional[bool] = Field(
        None,
        description='Indicates if a metric is invisible in the report response. If a metric is invisible, the metric will not produce a column in the response, but can be used in `metricFilter`, `orderBys`, or a metric `expression`.',
    )
    name: Optional[str] = Field(
        None,
        description="The name of the metric. See the [API Metrics](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema#metrics) for the list of metric names. If `expression` is specified, `name` can be any string that you would like within the allowed character set. For example if `expression` is `screenPageViews/sessions`, you could call that metric's name = `viewsPerSession`. Metric names that you choose must match the regular expression `^[a-zA-Z0-9_]$`. Metrics are referenced by `name` in `metricFilter`, `orderBys`, and metric `expression`.",
    )


class Type(Enum):
    METRIC_TYPE_UNSPECIFIED = 'METRIC_TYPE_UNSPECIFIED'
    TYPE_INTEGER = 'TYPE_INTEGER'
    TYPE_FLOAT = 'TYPE_FLOAT'
    TYPE_SECONDS = 'TYPE_SECONDS'
    TYPE_MILLISECONDS = 'TYPE_MILLISECONDS'
    TYPE_MINUTES = 'TYPE_MINUTES'
    TYPE_HOURS = 'TYPE_HOURS'
    TYPE_STANDARD = 'TYPE_STANDARD'
    TYPE_CURRENCY = 'TYPE_CURRENCY'
    TYPE_FEET = 'TYPE_FEET'
    TYPE_MILES = 'TYPE_MILES'
    TYPE_METERS = 'TYPE_METERS'
    TYPE_KILOMETERS = 'TYPE_KILOMETERS'


class MetricHeader(BaseModel):
    name: Optional[str] = Field(None, description="The metric's name.")
    type: Optional[Type] = Field(None, description="The metric's data type.")


class BlockedReason(Enum):
    BLOCKED_REASON_UNSPECIFIED = 'BLOCKED_REASON_UNSPECIFIED'
    NO_REVENUE_METRICS = 'NO_REVENUE_METRICS'
    NO_COST_METRICS = 'NO_COST_METRICS'


class MetricMetadata(BaseModel):
    apiName: Optional[str] = Field(
        None,
        description="A metric name. Useable in [Metric](#Metric)'s `name`. For example, `eventCount`.",
    )
    blockedReasons: Optional[List[BlockedReason]] = Field(
        None,
        description='If reasons are specified, your access is blocked to this metric for this property. API requests from you to this property for this metric will succeed; however, the report will contain only zeros for this metric. API requests with metric filters on blocked metrics will fail. If reasons are empty, you have access to this metric. To learn more, see [Access and data-restriction management](https://support.google.com/analytics/answer/10851388).',
    )
    category: Optional[str] = Field(
        None,
        description='The display name of the category that this metrics belongs to. Similar dimensions and metrics are categorized together.',
    )
    customDefinition: Optional[bool] = Field(
        None, description='True if the metric is a custom metric for this property.'
    )
    deprecatedApiNames: Optional[List[str]] = Field(
        None,
        description='Still usable but deprecated names for this metric. If populated, this metric is available by either `apiName` or one of `deprecatedApiNames` for a period of time. After the deprecation period, the metric will be available only by `apiName`.',
    )
    description: Optional[str] = Field(
        None, description='Description of how this metric is used and calculated.'
    )
    expression: Optional[str] = Field(
        None,
        description="The mathematical expression for this derived metric. Can be used in [Metric](#Metric)'s `expression` field for equivalent reports. Most metrics are not expressions, and for non-expressions, this field is empty.",
    )
    type: Optional[Type] = Field(None, description='The type of this metric.')
    uiName: Optional[str] = Field(
        None,
        description="This metric's name within the Google Analytics user interface. For example, `Event count`.",
    )


class MetricOrderBy(BaseModel):
    metricName: Optional[str] = Field(
        None, description='A metric name in the request to order by.'
    )


class MetricValue(BaseModel):
    value: Optional[str] = Field(
        None, description='Measurement value. See MetricHeader for type.'
    )


class MinuteRange(BaseModel):
    endMinutesAgo: Optional[int] = Field(
        None,
        description='The inclusive end minute for the query as a number of minutes before now. Cannot be before `startMinutesAgo`. For example, `"endMinutesAgo": 15` specifies the report should include event data from prior to 15 minutes ago. If unspecified, `endMinutesAgo` is defaulted to 0. Standard Analytics properties can request any minute in the last 30 minutes of event data (`endMinutesAgo <= 29`), and 360 Analytics properties can request any minute in the last 60 minutes of event data (`endMinutesAgo <= 59`).',
    )
    name: Optional[str] = Field(
        None,
        description='Assigns a name to this minute range. The dimension `dateRange` is valued to this name in a report response. If set, cannot begin with `date_range_` or `RESERVED_`. If not set, minute ranges are named by their zero based index in the request: `date_range_0`, `date_range_1`, etc.',
    )
    startMinutesAgo: Optional[int] = Field(
        None,
        description='The inclusive start minute for the query as a number of minutes before now. For example, `"startMinutesAgo": 29` specifies the report should include event data from 29 minutes ago and after. Cannot be after `endMinutesAgo`. If unspecified, `startMinutesAgo` is defaulted to 29. Standard Analytics properties can request up to the last 30 minutes of event data (`startMinutesAgo <= 29`), and 360 Analytics properties can request up to the last 60 minutes of event data (`startMinutesAgo <= 59`).',
    )


class Operation(Enum):
    OPERATION_UNSPECIFIED = 'OPERATION_UNSPECIFIED'
    EQUAL = 'EQUAL'
    LESS_THAN = 'LESS_THAN'
    LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL'
    GREATER_THAN = 'GREATER_THAN'
    GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL'


class NumericValue(BaseModel):
    doubleValue: Optional[float] = Field(None, description='Double value')
    int64Value: Optional[str] = Field(None, description='Integer value')


class MetricAggregation(Enum):
    METRIC_AGGREGATION_UNSPECIFIED = 'METRIC_AGGREGATION_UNSPECIFIED'
    TOTAL = 'TOTAL'
    MINIMUM = 'MINIMUM'
    MAXIMUM = 'MAXIMUM'
    COUNT = 'COUNT'


class PivotDimensionHeader(BaseModel):
    dimensionValues: Optional[List[DimensionValue]] = Field(
        None, description='Values of multiple dimensions in a pivot.'
    )


class PivotHeader(BaseModel):
    pivotDimensionHeaders: Optional[List[PivotDimensionHeader]] = Field(
        None,
        description='The size is the same as the cardinality of the corresponding dimension combinations.',
    )
    rowCount: Optional[int] = Field(
        None,
        description="The cardinality of the pivot. The total number of rows for this pivot's fields regardless of how the parameters `offset` and `limit` are specified in the request.",
    )


class PivotSelection(BaseModel):
    dimensionName: Optional[str] = Field(
        None, description='Must be a dimension name from the request.'
    )
    dimensionValue: Optional[str] = Field(
        None, description='Order by only when the named dimension is this value.'
    )


class QuotaStatus(BaseModel):
    consumed: Optional[int] = Field(None, description='Quota consumed by this request.')
    remaining: Optional[int] = Field(
        None, description='Quota remaining after this request.'
    )


class Row(BaseModel):
    dimensionValues: Optional[List[DimensionValue]] = Field(
        None,
        description='List of requested dimension values. In a PivotReport, dimension_values are only listed for dimensions included in a pivot.',
    )
    metricValues: Optional[List[MetricValue]] = Field(
        None, description='List of requested visible metric values.'
    )


class SchemaRestrictionResponse(BaseModel):
    activeMetricRestrictions: Optional[List[ActiveMetricRestriction]] = Field(
        None,
        description="All restrictions actively enforced in creating the report. For example, `purchaseRevenue` always has the restriction type `REVENUE_DATA`. However, this active response restriction is only populated if the user's custom role disallows access to `REVENUE_DATA`.",
    )


class MatchType(Enum):
    MATCH_TYPE_UNSPECIFIED = 'MATCH_TYPE_UNSPECIFIED'
    EXACT = 'EXACT'
    BEGINS_WITH = 'BEGINS_WITH'
    ENDS_WITH = 'ENDS_WITH'
    CONTAINS = 'CONTAINS'
    FULL_REGEXP = 'FULL_REGEXP'
    PARTIAL_REGEXP = 'PARTIAL_REGEXP'


class StringFilter(BaseModel):
    caseSensitive: Optional[bool] = Field(
        None, description='If true, the string value is case sensitive.'
    )
    matchType: Optional[MatchType] = Field(
        None, description='The match type for this filter.'
    )
    value: Optional[str] = Field(
        None, description='The string value used for the matching.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class BetweenFilter(BaseModel):
    fromValue: Optional[NumericValue] = Field(
        None, description='Begins with this number.'
    )
    toValue: Optional[NumericValue] = Field(None, description='Ends with this number.')


class Cohort(BaseModel):
    dateRange: Optional[DateRange] = Field(
        None,
        description="The cohort selects users whose first touch date is between start date and end date defined in the `dateRange`. This `dateRange` does not specify the full date range of event data that is present in a cohort report. In a cohort report, this `dateRange` is extended by the granularity and offset present in the `cohortsRange`; event data for the extended reporting date range is present in a cohort report. In a cohort request, this `dateRange` is required and the `dateRanges` in the `RunReportRequest` or `RunPivotReportRequest` must be unspecified. This `dateRange` should generally be aligned with the cohort's granularity. If `CohortsRange` uses daily granularity, this `dateRange` can be a single day. If `CohortsRange` uses weekly granularity, this `dateRange` can be aligned to a week boundary, starting at Sunday and ending Saturday. If `CohortsRange` uses monthly granularity, this `dateRange` can be aligned to a month, starting at the first and ending on the last day of the month.",
    )
    dimension: Optional[str] = Field(
        None,
        description='Dimension used by the cohort. Required and only supports `firstSessionDate`.',
    )
    name: Optional[str] = Field(
        None,
        description='Assigns a name to this cohort. The dimension `cohort` is valued to this name in a report response. If set, cannot begin with `cohort_` or `RESERVED_`. If not set, cohorts are named by their zero based index `cohort_0`, `cohort_1`, etc.',
    )


class CohortSpec(BaseModel):
    cohortReportSettings: Optional[CohortReportSettings] = Field(
        None, description='Optional settings for a cohort report.'
    )
    cohorts: Optional[List[Cohort]] = Field(
        None,
        description='Defines the selection criteria to group users into cohorts. Most cohort reports define only a single cohort. If multiple cohorts are specified, each cohort can be recognized in the report by their name.',
    )
    cohortsRange: Optional[CohortsRange] = Field(
        None,
        description='Cohort reports follow cohorts over an extended reporting date range. This range specifies an offset duration to follow the cohorts over.',
    )


class Dimension(BaseModel):
    dimensionExpression: Optional[DimensionExpression] = Field(
        None,
        description='One dimension can be the result of an expression of multiple dimensions. For example, dimension "country, city": concatenate(country, ", ", city).',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the dimension. See the [API Dimensions](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema#dimensions) for the list of dimension names. If `dimensionExpression` is specified, `name` can be any string that you would like within the allowed character set. For example if a `dimensionExpression` concatenates `country` and `city`, you could call that dimension `countryAndCity`. Dimension names that you choose must match the regular expression `^[a-zA-Z0-9_]$`. Dimensions are referenced by `name` in `dimensionFilter`, `orderBys`, `dimensionExpression`, and `pivots`.',
    )


class DimensionCompatibility(BaseModel):
    compatibility: Optional[Compatibility] = Field(
        None,
        description='The compatibility of this dimension. If the compatibility is COMPATIBLE, this dimension can be successfully added to the report.',
    )
    dimensionMetadata: Optional[DimensionMetadata] = Field(
        None,
        description='The dimension metadata contains the API name for this compatibility information. The dimension metadata also contains other helpful information like the UI name and description.',
    )


class Metadata(BaseModel):
    dimensions: Optional[List[DimensionMetadata]] = Field(
        None, description='The dimension descriptions.'
    )
    metrics: Optional[List[MetricMetadata]] = Field(
        None, description='The metric descriptions.'
    )
    name: Optional[str] = Field(None, description='Resource name of this metadata.')


class MetricCompatibility(BaseModel):
    compatibility: Optional[Compatibility] = Field(
        None,
        description='The compatibility of this metric. If the compatibility is COMPATIBLE, this metric can be successfully added to the report.',
    )
    metricMetadata: Optional[MetricMetadata] = Field(
        None,
        description='The metric metadata contains the API name for this compatibility information. The metric metadata also contains other helpful information like the UI name and description.',
    )


class NumericFilter(BaseModel):
    operation: Optional[Operation] = Field(
        None, description='The operation type for this filter.'
    )
    value: Optional[NumericValue] = Field(
        None, description='A numeric value or a date value.'
    )


class PivotOrderBy(BaseModel):
    metricName: Optional[str] = Field(
        None,
        description='In the response to order by, order rows by this column. Must be a metric name from the request.',
    )
    pivotSelections: Optional[List[PivotSelection]] = Field(
        None,
        description="Used to select a dimension name and value pivot. If multiple pivot selections are given, the sort occurs on rows where all pivot selection dimension name and value pairs match the row's dimension name and value pair.",
    )


class PropertyQuota(BaseModel):
    concurrentRequests: Optional[QuotaStatus] = Field(
        None,
        description='Standard Analytics Properties can send up to 10 concurrent requests; Analytics 360 Properties can use up to 50 concurrent requests.',
    )
    potentiallyThresholdedRequestsPerHour: Optional[QuotaStatus] = Field(
        None,
        description='Analytics Properties can send up to 120 requests with potentially thresholded dimensions per hour. In a batch request, each report request is individually counted for this quota if the request contains potentially thresholded dimensions.',
    )
    serverErrorsPerProjectPerHour: Optional[QuotaStatus] = Field(
        None,
        description='Standard Analytics Properties and cloud project pairs can have up to 10 server errors per hour; Analytics 360 Properties and cloud project pairs can have up to 50 server errors per hour.',
    )
    tokensPerDay: Optional[QuotaStatus] = Field(
        None,
        description='Standard Analytics Properties can use up to 25,000 tokens per day; Analytics 360 Properties can use 250,000 tokens per day. Most requests consume fewer than 10 tokens.',
    )
    tokensPerHour: Optional[QuotaStatus] = Field(
        None,
        description='Standard Analytics Properties can use up to 5,000 tokens per hour; Analytics 360 Properties can use 50,000 tokens per hour. An API request consumes a single number of tokens, and that number is deducted from all of the hourly, daily, and per project hourly quotas.',
    )
    tokensPerProjectPerHour: Optional[QuotaStatus] = Field(
        None,
        description='Analytics Properties can use up to 25% of their tokens per project per hour. This amounts to standard Analytics Properties can use up to 1,250 tokens per project per hour, and Analytics 360 Properties can use 12,500 tokens per project per hour. An API request consumes a single number of tokens, and that number is deducted from all of the hourly, daily, and per project hourly quotas.',
    )


class ResponseMetaData(BaseModel):
    currencyCode: Optional[str] = Field(
        None,
        description='The currency code used in this report. Intended to be used in formatting currency metrics like `purchaseRevenue` for visualization. If currency_code was specified in the request, this response parameter will echo the request parameter; otherwise, this response parameter is the property\'s current currency_code. Currency codes are string encodings of currency types from the ISO 4217 standard (https://en.wikipedia.org/wiki/ISO_4217); for example "USD", "EUR", "JPY". To learn more, see https://support.google.com/analytics/answer/9796179.',
    )
    dataLossFromOtherRow: Optional[bool] = Field(
        None,
        description='If true, indicates some buckets of dimension combinations are rolled into "(other)" row. This can happen for high cardinality reports. The metadata parameter dataLossFromOtherRow is populated based on the aggregated data table used in the report. The parameter will be accurately populated regardless of the filters and limits in the report. For example, the (other) row could be dropped from the report because the request contains a filter on sessionSource = google. This parameter will still be populated if data loss from other row was present in the input aggregate data used to generate this report. To learn more, see [About the (other) row and data sampling](https://support.google.com/analytics/answer/13208658#reports).',
    )
    emptyReason: Optional[str] = Field(
        None,
        description='If empty reason is specified, the report is empty for this reason.',
    )
    schemaRestrictionResponse: Optional[SchemaRestrictionResponse] = Field(
        None,
        description='Describes the schema restrictions actively enforced in creating this report. To learn more, see [Access and data-restriction management](https://support.google.com/analytics/answer/10851388).',
    )
    subjectToThresholding: Optional[bool] = Field(
        None,
        description='If `subjectToThresholding` is true, this report is subject to thresholding and only returns data that meets the minimum aggregation thresholds. It is possible for a request to be subject to thresholding thresholding and no data is absent from the report, and this happens when all data is above the thresholds. To learn more, see [Data thresholds](https://support.google.com/analytics/answer/9383630) and [About Demographics and Interests](https://support.google.com/analytics/answer/2799357).',
    )
    timeZone: Optional[str] = Field(
        None,
        description='The property\'s current timezone. Intended to be used to interpret time-based dimensions like `hour` and `minute`. Formatted as strings from the IANA Time Zone database (https://www.iana.org/time-zones); for example "America/New_York" or "Asia/Tokyo".',
    )


class RunPivotReportResponse(BaseModel):
    aggregates: Optional[List[Row]] = Field(
        None,
        description='Aggregation of metric values. Can be totals, minimums, or maximums. The returned aggregations are controlled by the metric_aggregations in the pivot. The type of aggregation returned in each row is shown by the dimension_values which are set to "RESERVED_".',
    )
    dimensionHeaders: Optional[List[DimensionHeader]] = Field(
        None,
        description='Describes dimension columns. The number of DimensionHeaders and ordering of DimensionHeaders matches the dimensions present in rows.',
    )
    kind: Optional[str] = Field(
        None,
        description='Identifies what kind of resource this message is. This `kind` is always the fixed string "analyticsData#runPivotReport". Useful to distinguish between response types in JSON.',
    )
    metadata: Optional[ResponseMetaData] = Field(
        None, description='Metadata for the report.'
    )
    metricHeaders: Optional[List[MetricHeader]] = Field(
        None,
        description='Describes metric columns. The number of MetricHeaders and ordering of MetricHeaders matches the metrics present in rows.',
    )
    pivotHeaders: Optional[List[PivotHeader]] = Field(
        None,
        description='Summarizes the columns and rows created by a pivot. Each pivot in the request produces one header in the response. If we have a request like this: "pivots": [{ "fieldNames": ["country", "city"] }, { "fieldNames": "eventName" }] We will have the following `pivotHeaders` in the response: "pivotHeaders" : [{ "dimensionHeaders": [{ "dimensionValues": [ { "value": "United Kingdom" }, { "value": "London" } ] }, { "dimensionValues": [ { "value": "Japan" }, { "value": "Osaka" } ] }] }, { "dimensionHeaders": [{ "dimensionValues": [{ "value": "session_start" }] }, { "dimensionValues": [{ "value": "scroll" }] }] }]',
    )
    propertyQuota: Optional[PropertyQuota] = Field(
        None,
        description="This Analytics Property's quota state including this request.",
    )
    rows: Optional[List[Row]] = Field(
        None,
        description='Rows of dimension value combinations and metric values in the report.',
    )


class RunRealtimeReportResponse(BaseModel):
    dimensionHeaders: Optional[List[DimensionHeader]] = Field(
        None,
        description='Describes dimension columns. The number of DimensionHeaders and ordering of DimensionHeaders matches the dimensions present in rows.',
    )
    kind: Optional[str] = Field(
        None,
        description='Identifies what kind of resource this message is. This `kind` is always the fixed string "analyticsData#runRealtimeReport". Useful to distinguish between response types in JSON.',
    )
    maximums: Optional[List[Row]] = Field(
        None, description='If requested, the maximum values of metrics.'
    )
    metricHeaders: Optional[List[MetricHeader]] = Field(
        None,
        description='Describes metric columns. The number of MetricHeaders and ordering of MetricHeaders matches the metrics present in rows.',
    )
    minimums: Optional[List[Row]] = Field(
        None, description='If requested, the minimum values of metrics.'
    )
    propertyQuota: Optional[PropertyQuota] = Field(
        None,
        description="This Analytics Property's Realtime quota state including this request.",
    )
    rowCount: Optional[int] = Field(
        None,
        description='The total number of rows in the query result. `rowCount` is independent of the number of rows returned in the response and the `limit` request parameter. For example if a query returns 175 rows and includes `limit` of 50 in the API request, the response will contain `rowCount` of 175 but only 50 rows.',
    )
    rows: Optional[List[Row]] = Field(
        None,
        description='Rows of dimension value combinations and metric values in the report.',
    )
    totals: Optional[List[Row]] = Field(
        None, description='If requested, the totaled values of metrics.'
    )


class RunReportResponse(BaseModel):
    dimensionHeaders: Optional[List[DimensionHeader]] = Field(
        None,
        description='Describes dimension columns. The number of DimensionHeaders and ordering of DimensionHeaders matches the dimensions present in rows.',
    )
    kind: Optional[str] = Field(
        None,
        description='Identifies what kind of resource this message is. This `kind` is always the fixed string "analyticsData#runReport". Useful to distinguish between response types in JSON.',
    )
    maximums: Optional[List[Row]] = Field(
        None, description='If requested, the maximum values of metrics.'
    )
    metadata: Optional[ResponseMetaData] = Field(
        None, description='Metadata for the report.'
    )
    metricHeaders: Optional[List[MetricHeader]] = Field(
        None,
        description='Describes metric columns. The number of MetricHeaders and ordering of MetricHeaders matches the metrics present in rows.',
    )
    minimums: Optional[List[Row]] = Field(
        None, description='If requested, the minimum values of metrics.'
    )
    propertyQuota: Optional[PropertyQuota] = Field(
        None,
        description="This Analytics Property's quota state including this request.",
    )
    rowCount: Optional[int] = Field(
        None,
        description='The total number of rows in the query result. `rowCount` is independent of the number of rows returned in the response, the `limit` request parameter, and the `offset` request parameter. For example if a query returns 175 rows and includes `limit` of 50 in the API request, the response will contain `rowCount` of 175 but only 50 rows. To learn more about this pagination parameter, see [Pagination](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#pagination).',
    )
    rows: Optional[List[Row]] = Field(
        None,
        description='Rows of dimension value combinations and metric values in the report.',
    )
    totals: Optional[List[Row]] = Field(
        None, description='If requested, the totaled values of metrics.'
    )


class BatchRunPivotReportsResponse(BaseModel):
    kind: Optional[str] = Field(
        None,
        description='Identifies what kind of resource this message is. This `kind` is always the fixed string "analyticsData#batchRunPivotReports". Useful to distinguish between response types in JSON.',
    )
    pivotReports: Optional[List[RunPivotReportResponse]] = Field(
        None,
        description='Individual responses. Each response has a separate pivot report request.',
    )


class BatchRunReportsResponse(BaseModel):
    kind: Optional[str] = Field(
        None,
        description='Identifies what kind of resource this message is. This `kind` is always the fixed string "analyticsData#batchRunReports". Useful to distinguish between response types in JSON.',
    )
    reports: Optional[List[RunReportResponse]] = Field(
        None,
        description='Individual responses. Each response has a separate report request.',
    )


class CheckCompatibilityResponse(BaseModel):
    dimensionCompatibilities: Optional[List[DimensionCompatibility]] = Field(
        None, description='The compatibility of each dimension.'
    )
    metricCompatibilities: Optional[List[MetricCompatibility]] = Field(
        None, description='The compatibility of each metric.'
    )


class Filter(BaseModel):
    betweenFilter: Optional[BetweenFilter] = Field(
        None, description='A filter for two values.'
    )
    fieldName: Optional[str] = Field(
        None,
        description="The dimension name or metric name. In most methods, dimensions & metrics can be used for the first time in this field. However in a RunPivotReportRequest, this field must be additionally specified by name in the RunPivotReportRequest's dimensions or metrics.",
    )
    inListFilter: Optional[InListFilter] = Field(
        None, description='A filter for in list values.'
    )
    numericFilter: Optional[NumericFilter] = Field(
        None, description='A filter for numeric or date values.'
    )
    stringFilter: Optional[StringFilter] = Field(
        None, description='Strings related filter.'
    )


class OrderBy(BaseModel):
    desc: Optional[bool] = Field(
        None, description='If true, sorts by descending order.'
    )
    dimension: Optional[DimensionOrderBy] = Field(
        None, description="Sorts results by a dimension's values."
    )
    metric: Optional[MetricOrderBy] = Field(
        None, description="Sorts results by a metric's values."
    )
    pivot: Optional[PivotOrderBy] = Field(
        None,
        description="Sorts results by a metric's values within a pivot column group.",
    )


class Pivot(BaseModel):
    fieldNames: Optional[List[str]] = Field(
        None,
        description='Dimension names for visible columns in the report response. Including "dateRange" produces a date range column; for each row in the response, dimension values in the date range column will indicate the corresponding date range from the request.',
    )
    limit: Optional[str] = Field(
        None,
        description='The number of unique combinations of dimension values to return in this pivot. The `limit` parameter is required. A `limit` of 10,000 is common for single pivot requests. The product of the `limit` for each `pivot` in a `RunPivotReportRequest` must not exceed 250,000. For example, a two pivot request with `limit: 1000` in each pivot will fail because the product is `1,000,000`.',
    )
    metricAggregations: Optional[List[MetricAggregation]] = Field(
        None,
        description='Aggregate the metrics by dimensions in this pivot using the specified metric_aggregations.',
    )
    offset: Optional[str] = Field(
        None,
        description='The row count of the start row. The first row is counted as row 0.',
    )
    orderBys: Optional[List[OrderBy]] = Field(
        None,
        description='Specifies how dimensions are ordered in the pivot. In the first Pivot, the OrderBys determine Row and PivotDimensionHeader ordering; in subsequent Pivots, the OrderBys determine only PivotDimensionHeader ordering. Dimensions specified in these OrderBys must be a subset of Pivot.field_names.',
    )


class BatchRunPivotReportsRequest(BaseModel):
    requests: Optional[List[RunPivotReportRequest]] = Field(
        None,
        description='Individual requests. Each request has a separate pivot report response. Each batch request is allowed up to 5 requests.',
    )


class BatchRunReportsRequest(BaseModel):
    requests: Optional[List[RunReportRequest]] = Field(
        None,
        description='Individual requests. Each request has a separate report response. Each batch request is allowed up to 5 requests.',
    )


class CheckCompatibilityRequest(BaseModel):
    compatibilityFilter: Optional[CompatibilityFilter] = Field(
        None,
        description='Filters the dimensions and metrics in the response to just this compatibility. Commonly used as `”compatibilityFilter”: “COMPATIBLE”` to only return compatible dimensions & metrics.',
    )
    dimensionFilter: Optional[FilterExpression] = Field(
        None,
        description='The filter clause of dimensions. `dimensionFilter` should be the same value as in your `runReport` request.',
    )
    dimensions: Optional[List[Dimension]] = Field(
        None,
        description='The dimensions in this report. `dimensions` should be the same value as in your `runReport` request.',
    )
    metricFilter: Optional[FilterExpression] = Field(
        None,
        description='The filter clause of metrics. `metricFilter` should be the same value as in your `runReport` request',
    )
    metrics: Optional[List[Metric]] = Field(
        None,
        description='The metrics in this report. `metrics` should be the same value as in your `runReport` request.',
    )


class FilterExpression(BaseModel):
    andGroup: Optional[FilterExpressionList] = Field(
        None, description='The FilterExpressions in and_group have an AND relationship.'
    )
    filter: Optional[Filter] = Field(
        None,
        description="A primitive filter. In the same FilterExpression, all of the filter's field names need to be either all dimensions or all metrics.",
    )
    notExpression: Optional[FilterExpression] = Field(
        None, description='The FilterExpression is NOT of not_expression.'
    )
    orGroup: Optional[FilterExpressionList] = Field(
        None, description='The FilterExpressions in or_group have an OR relationship.'
    )


class FilterExpressionList(BaseModel):
    expressions: Optional[List[FilterExpression]] = Field(
        None, description='A list of filter expressions.'
    )


class RunPivotReportRequest(BaseModel):
    cohortSpec: Optional[CohortSpec] = Field(
        None,
        description="Cohort group associated with this request. If there is a cohort group in the request the 'cohort' dimension must be present.",
    )
    currencyCode: Optional[str] = Field(
        None,
        description='A currency code in ISO4217 format, such as "AED", "USD", "JPY". If the field is empty, the report uses the property\'s default currency.',
    )
    dateRanges: Optional[List[DateRange]] = Field(
        None,
        description='The date range to retrieve event data for the report. If multiple date ranges are specified, event data from each date range is used in the report. A special dimension with field name "dateRange" can be included in a Pivot\'s field names; if included, the report compares between date ranges. In a cohort request, this `dateRanges` must be unspecified.',
    )
    dimensionFilter: Optional[FilterExpression] = Field(
        None,
        description='The filter clause of dimensions. Dimensions must be requested to be used in this filter. Metrics cannot be used in this filter.',
    )
    dimensions: Optional[List[Dimension]] = Field(
        None,
        description='The dimensions requested. All defined dimensions must be used by one of the following: dimension_expression, dimension_filter, pivots, order_bys.',
    )
    keepEmptyRows: Optional[bool] = Field(
        None,
        description='If false or unspecified, each row with all metrics equal to 0 will not be returned. If true, these rows will be returned if they are not separately removed by a filter. Regardless of this `keep_empty_rows` setting, only data recorded by the Google Analytics (GA4) property can be displayed in a report. For example if a property never logs a `purchase` event, then a query for the `eventName` dimension and `eventCount` metric will not have a row eventName: "purchase" and eventCount: 0.',
    )
    metricFilter: Optional[FilterExpression] = Field(
        None,
        description='The filter clause of metrics. Applied at post aggregation phase, similar to SQL having-clause. Metrics must be requested to be used in this filter. Dimensions cannot be used in this filter.',
    )
    metrics: Optional[List[Metric]] = Field(
        None,
        description='The metrics requested, at least one metric needs to be specified. All defined metrics must be used by one of the following: metric_expression, metric_filter, order_bys.',
    )
    pivots: Optional[List[Pivot]] = Field(
        None,
        description="Describes the visual format of the report's dimensions in columns or rows. The union of the fieldNames (dimension names) in all pivots must be a subset of dimension names defined in Dimensions. No two pivots can share a dimension. A dimension is only visible if it appears in a pivot.",
    )
    property: Optional[str] = Field(
        None,
        description='A Google Analytics GA4 property identifier whose events are tracked. Specified in the URL path and not the body. To learn more, see [where to find your Property ID](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id). Within a batch request, this property should either be unspecified or consistent with the batch-level property. Example: properties/1234',
    )
    returnPropertyQuota: Optional[bool] = Field(
        None,
        description="Toggles whether to return the current state of this Analytics Property's quota. Quota is returned in [PropertyQuota](#PropertyQuota).",
    )


class RunRealtimeReportRequest(BaseModel):
    dimensionFilter: Optional[FilterExpression] = Field(
        None,
        description='The filter clause of dimensions. Metrics cannot be used in this filter.',
    )
    dimensions: Optional[List[Dimension]] = Field(
        None, description='The dimensions requested and displayed.'
    )
    limit: Optional[str] = Field(
        None,
        description="The number of rows to return. If unspecified, 10,000 rows are returned. The API returns a maximum of 250,000 rows per request, no matter how many you ask for. `limit` must be positive. The API can also return fewer rows than the requested `limit`, if there aren't as many dimension values as the `limit`. For instance, there are fewer than 300 possible values for the dimension `country`, so when reporting on only `country`, you can't get more than 300 rows, even if you set `limit` to a higher value.",
    )
    metricAggregations: Optional[List[MetricAggregation]] = Field(
        None,
        description='Aggregation of metrics. Aggregated metric values will be shown in rows where the dimension_values are set to "RESERVED_(MetricAggregation)".',
    )
    metricFilter: Optional[FilterExpression] = Field(
        None,
        description='The filter clause of metrics. Applied at post aggregation phase, similar to SQL having-clause. Dimensions cannot be used in this filter.',
    )
    metrics: Optional[List[Metric]] = Field(
        None, description='The metrics requested and displayed.'
    )
    minuteRanges: Optional[List[MinuteRange]] = Field(
        None,
        description='The minute ranges of event data to read. If unspecified, one minute range for the last 30 minutes will be used. If multiple minute ranges are requested, each response row will contain a zero based minute range index. If two minute ranges overlap, the event data for the overlapping minutes is included in the response rows for both minute ranges.',
    )
    orderBys: Optional[List[OrderBy]] = Field(
        None, description='Specifies how rows are ordered in the response.'
    )
    returnPropertyQuota: Optional[bool] = Field(
        None,
        description="Toggles whether to return the current state of this Analytics Property's Realtime quota. Quota is returned in [PropertyQuota](#PropertyQuota).",
    )


class RunReportRequest(BaseModel):
    cohortSpec: Optional[CohortSpec] = Field(
        None,
        description="Cohort group associated with this request. If there is a cohort group in the request the 'cohort' dimension must be present.",
    )
    currencyCode: Optional[str] = Field(
        None,
        description='A currency code in ISO4217 format, such as "AED", "USD", "JPY". If the field is empty, the report uses the property\'s default currency.',
    )
    dateRanges: Optional[List[DateRange]] = Field(
        None,
        description='Date ranges of data to read. If multiple date ranges are requested, each response row will contain a zero based date range index. If two date ranges overlap, the event data for the overlapping days is included in the response rows for both date ranges. In a cohort request, this `dateRanges` must be unspecified.',
    )
    dimensionFilter: Optional[FilterExpression] = Field(
        None,
        description='Dimension filters let you ask for only specific dimension values in the report. To learn more, see [Fundamentals of Dimension Filters](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#dimension_filters) for examples. Metrics cannot be used in this filter.',
    )
    dimensions: Optional[List[Dimension]] = Field(
        None, description='The dimensions requested and displayed.'
    )
    keepEmptyRows: Optional[bool] = Field(
        None,
        description='If false or unspecified, each row with all metrics equal to 0 will not be returned. If true, these rows will be returned if they are not separately removed by a filter. Regardless of this `keep_empty_rows` setting, only data recorded by the Google Analytics (GA4) property can be displayed in a report. For example if a property never logs a `purchase` event, then a query for the `eventName` dimension and `eventCount` metric will not have a row eventName: "purchase" and eventCount: 0.',
    )
    limit: Optional[str] = Field(
        None,
        description="The number of rows to return. If unspecified, 10,000 rows are returned. The API returns a maximum of 250,000 rows per request, no matter how many you ask for. `limit` must be positive. The API can also return fewer rows than the requested `limit`, if there aren't as many dimension values as the `limit`. For instance, there are fewer than 300 possible values for the dimension `country`, so when reporting on only `country`, you can't get more than 300 rows, even if you set `limit` to a higher value. To learn more about this pagination parameter, see [Pagination](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#pagination).",
    )
    metricAggregations: Optional[List[MetricAggregation]] = Field(
        None,
        description='Aggregation of metrics. Aggregated metric values will be shown in rows where the dimension_values are set to "RESERVED_(MetricAggregation)".',
    )
    metricFilter: Optional[FilterExpression] = Field(
        None,
        description="The filter clause of metrics. Applied after aggregating the report's rows, similar to SQL having-clause. Dimensions cannot be used in this filter.",
    )
    metrics: Optional[List[Metric]] = Field(
        None, description='The metrics requested and displayed.'
    )
    offset: Optional[str] = Field(
        None,
        description='The row count of the start row. The first row is counted as row 0. When paging, the first request does not specify offset; or equivalently, sets offset to 0; the first request returns the first `limit` of rows. The second request sets offset to the `limit` of the first request; the second request returns the second `limit` of rows. To learn more about this pagination parameter, see [Pagination](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#pagination).',
    )
    orderBys: Optional[List[OrderBy]] = Field(
        None, description='Specifies how rows are ordered in the response.'
    )
    property: Optional[str] = Field(
        None,
        description='A Google Analytics GA4 property identifier whose events are tracked. Specified in the URL path and not the body. To learn more, see [where to find your Property ID](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id). Within a batch request, this property should either be unspecified or consistent with the batch-level property. Example: properties/1234',
    )
    returnPropertyQuota: Optional[bool] = Field(
        None,
        description="Toggles whether to return the current state of this Analytics Property's quota. Quota is returned in [PropertyQuota](#PropertyQuota).",
    )


BatchRunPivotReportsRequest.model_rebuild()
BatchRunReportsRequest.model_rebuild()
CheckCompatibilityRequest.model_rebuild()
FilterExpression.model_rebuild()
